name: Build and Test ToiLabs Docker Stack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker (Compose v2 included)
        uses: docker/setup-docker-action@v2

      - name: Log in to GitHub Container Registry (optional)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all services
        run: docker compose -f docker-compose.yml build --no-cache

      - name: Run containers
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 30
          docker ps -a

      - name: Shutdown containers
        if: always()
        run: docker compose -f docker-compose.yml down
