name: Build and Test ToiLabs Docker Stack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry (optional)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all services from docker-compose
        run: |
          docker-compose -f docker-compose.yml build --no-cache

      # Optional: Run containers and test health
      - name: Start containers (optional for smoke test)
        run: |
          docker-compose -f docker-compose.yml up -d
          sleep 30  # Wait for containers to stabilize
          docker ps -a

      - name: Cleanup
        if: always()
        run: docker-compose down
