name: Build, Test, and Push ToiLabs Docker Stack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker (Compose v2 included)
        uses: docker/setup-docker-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build all services using Docker Compose
        run: docker compose build --no-cache

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/toilabs-ml-model
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/toilabs-spring-backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/toilabs-frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/toilabs-airflow

      - name: Run containers (optional)
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 30
          docker ps -a

      - name: Shutdown containers
        if: always()
        run: docker compose -f docker-compose.yml down
